language: ruby
rvm:
- 2.1.1
- 2.0.0
script: bundle exec rake test
notifications:
  email: false
  irc:
    on_success: change
    on_failure: always
    channels:
    - irc.freenode.org#rubyonadhd
env:
  global:
    secure: ifm8+ChcdXB9BkuzordGulaZbkhhJzZpiqh8JnzgAg+KRPr/riEMQOi+wKAaJMyHobmQjPWbkUoeTaR4vMi/Sdf1sH2rc4NZHHInrfq6fjhNPI8cpykInhTb7hymBCZCQgXHzJKlnULWwJat7JNXrftq/PXQgWRVGiWmFbbNTw8=
